"""Real installed CLI/MCP, user YAML and ExifTool; generated media, zero providers."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import sqlite3
import subprocess

import anyio
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client
from PIL import Image
import yaml

import mediasense
from mediasense.manufacturers import KnowledgeSnapshot
from mediasense.runtime.resources import contract_validator


def make_source(root):
    root.mkdir()
    for name, make, day in [("acme", "ACME", 4), ("dji", "DJI", 5)]:
        exif = Image.Exif()
        exif[271], exif[272], exif[315] = make, "Synthetic", "Operator"
        exif[36867] = f"2026:05:0{day} 17:33:46"
        path = root / f"{name}.jpg"
        Image.new("RGB", (80, 40), "blue" if name == "acme" else "yellow").save(
            path, exif=exif
        )
        subprocess.run(
            [
                "exiftool",
                "-overwrite_original",
                f"-XMP:DateTimeOriginal=2026:05:0{day} 09:33:46+08:00",
                str(path),
            ],
            check=True,
            capture_output=True,
        )
    return {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in root.iterdir()}


def write_knowledge(path, shift=0, *, disable_dji=False):
    path.parent.mkdir(parents=True, exist_ok=True)
    rules = [
        {
            "id": "acme.installed",
            "operation": "add",
            "summary": "Synthetic installed-entry rule",
            "when": [{"tags": ["EXIF:Make"], "pattern": "^ACME$"}],
            "apply": {
                "capture_time": {
                    "tags": ["EXIF:DateTimeOriginal"],
                    "naive_time": "source_local",
                    "shift_seconds": shift,
                },
                "fields": [
                    {
                        "name": "manufacturer.acme.operator",
                        "tags": ["EXIF:Artist"],
                        "value_type": "string",
                        "description": "Synthetic device operator label",
                    }
                ],
            },
            "basis": {
                "sources": ["synthetic image generated by this test"],
                "limitations": [],
            },
        }
    ]
    if disable_dji:
        rules.append(
            {
                "id": "dji.photo-time",
                "operation": "disable",
                "reason": "Explicit installed conformance case",
            }
        )
    path.write_text(yaml.safe_dump({"schema_version": 1, "rules": rules}))


async def exercise(host, root):
    assert (
        Path(mediasense.__file__).resolve().is_relative_to(host.resolve().parent.parent)
    )
    source, workspace, config = root / "source", root / "dataset", root / "config"
    before = make_source(source)
    knowledge_path = config / "manufacturers" / "acme.yaml"
    write_knowledge(knowledge_path)
    env = {
        **os.environ,
        "MEDIASENSE_CONFIG_HOME": str(config),
        "MEDIASENSE_DATA_HOME": str(root / "data"),
        "AMAP_API_KEY": "",
        "GOOGLE_MAPS_API_KEY": "",
        "HF_HUB_OFFLINE": "1",
        "TRANSFORMERS_OFFLINE": "1",
    }
    env.pop("PYTHONPATH", None)
    doctor = subprocess.run(
        [str(host), "doctor", "--json"],
        env=env,
        cwd=root,
        capture_output=True,
        text=True,
    )
    diagnostic = json.loads(doctor.stdout)
    assert any(
        item.get("name") == "configuration" and item.get("status") != "error"
        for item in diagnostic["checks"]
    ), diagnostic
    params = StdioServerParameters(
        command=str(host), args=["mcp"], cwd=str(root), env=env
    )
    all_payloads = []
    async with (
        stdio_client(params) as (incoming, outgoing),
        ClientSession(incoming, outgoing) as session,
    ):
        await session.initialize()
        opened = await session.call_tool(
            "mediasense.dataset.open",
            {"source_root": str(source), "workspace": str(workspace)},
        )
        assert not opened.is_error and opened.content == [], opened
        opened_value = opened.structured_content
        dataset = opened_value["dataset_ref"]
        assert (
            "acme.installed"
            in opened_value["configuration"]["metadata"]["manufacturer_knowledge"][
                "active_rules"
            ]
        )
        assert len((await session.list_tools()).tools) == 7

        async def call(tool, action, *, expect_error=False, **values):
            response = await session.call_tool(
                "mediasense.precheck." + tool,
                {"action": action, "dataset_ref": dataset, **values},
            )
            assert bool(response.is_error) == expect_error, response
            assert response.content == [], response
            value = response.structured_content
            contract_validator("mediasense.precheck." + tool, action).validate(value)
            all_payloads.append(value)
            (root / "responses.json").write_text(
                json.dumps(all_payloads, ensure_ascii=False, indent=2)
            )
            return value

        async def wait(ref):
            with anyio.fail_after(90):
                while True:
                    state = await call("run", "status", run_ref=ref)
                    if state["state"] != "running":
                        return state
                    await anyio.sleep(0.05)

        async def run(index, prior=None):
            start = await call(
                "run",
                "start",
                request_id=f"manufacturer-smoke:{index}",
                **({"prior_result_ref": prior} if prior else {}),
            )
            assert "error" not in start, start
            state = await wait(start["run_ref"])
            if (
                state["state"] == "paused"
                and state.get("reason", {}).get("code") == "scope_confirmation_required"
            ):
                await call(
                    "run",
                    "resume",
                    run_ref=start["run_ref"],
                    decision={
                        "kind": "source_scope",
                        "inventory_fingerprint": state["confirmation"][
                            "inventory_fingerprint"
                        ],
                        "default_disposition": "include",
                        "exceptions": [],
                    },
                )
                state = await wait(start["run_ref"])
            assert state["state"] == "completed", state
            return start["run_ref"], state["result"]["ref"]

        async def read(result):
            page = await call("read", "review", result_ref=result)
            assert "error" not in page, page
            assert page["page"]["next_cursor"] is None, page
            assert all("source_items" in item for item in page["items"]), page
            sources = {
                source["locator"]["value"]: source
                for item in page["items"]
                for source in item["source_items"]
            }
            assert {"acme.jpg", "dji.jpg"} <= set(sources), sources
            return {
                path: {o["name"]: o for o in value["observations"]}
                for path, value in sources.items()
            }

        database = workspace / "precheck/work.sqlite3"

        def attempts():
            with sqlite3.connect(database) as connection:
                return connection.execute(
                    "SELECT count(*) FROM work_attempts"
                ).fetchone()[0]

        first_run, first_result = await run(1)
        first = await read(first_result)
        assert first["acme.jpg"]["capture_time"]["value"] == "2026-05-04T17:33:46+08:00"
        assert first["dji.jpg"]["capture_time"]["value"] == "2026-05-05T17:33:46+08:00"
        assert first["acme.jpg"]["manufacturer.acme.operator"]["value"] == "Operator"
        trace = first["acme.jpg"]["capture_time"]["provenance"][
            "manufacturer_knowledge"
        ]
        applied = next(
            item for item in trace["rules"] if item["id"] == "acme.installed"
        )
        assert applied["status"] == "applied"
        assert "source_item_ref" in applied["conditions"][0], applied
        with sqlite3.connect(database) as connection:
            frozen = json.loads(
                connection.execute(
                    "SELECT execution_config_json FROM precheck_runs WHERE run_ref=?",
                    (first_run,),
                ).fetchone()[0]
            )
        stored = KnowledgeSnapshot.from_value(
            frozen["metadata_profile"]["manufacturer_knowledge"]
        )
        assert stored.identity == trace["snapshot_identity"]
        before_attempts = attempts()
        _, second_result = await run(2, first_result)
        assert (await read(second_result))["acme.jpg"]["capture_time"][
            "value"
        ] == first["acme.jpg"]["capture_time"]["value"]
        assert attempts() == before_attempts

        write_knowledge(knowledge_path, shift=3600, disable_dji=True)
        _, third_result = await run(3, second_result)
        third = await read(third_result)
        assert third["acme.jpg"]["capture_time"]["value"] == "2026-05-04T18:33:46+08:00"
        assert third["dji.jpg"]["capture_time"]["value"] == "2026-05-05T09:33:46+08:00"
        assert (await read(first_result))["acme.jpg"]["capture_time"] == first[
            "acme.jpg"
        ]["capture_time"]
        assert (
            stored.identity
            != third["acme.jpg"]["capture_time"]["provenance"][
                "manufacturer_knowledge"
            ]["snapshot_identity"]
        )

        knowledge_path.write_text("invalid: true\n")
        replay = await call("run", "start", request_id="manufacturer-smoke:1")
        assert replay["run_ref"] == first_run
        invalid = await call(
            "run",
            "start",
            expect_error=True,
            request_id="manufacturer-smoke:invalid",
            prior_result_ref=third_result,
        )
        assert invalid["error"]["code"] == "configuration_invalid"
        assert {
            p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in source.iterdir()
        } == before
        knowledge_path.unlink()
        _, fourth_result = await run(4, third_result)
        fourth = await read(fourth_result)
        assert (
            fourth["acme.jpg"]["capture_time"]["value"] == "2026-05-04T09:33:46+08:00"
        )
        assert fourth["dji.jpg"]["capture_time"]["value"] == "2026-05-05T17:33:46+08:00"
        assert {
            p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in source.iterdir()
        } == before
    (root / "responses.json").write_text(
        json.dumps(all_payloads, ensure_ascii=False, indent=2)
    )
    (root / "summary.json").write_text(
        json.dumps(
            {
                "source_files": 2,
                "completed_runs": 4,
                "unchanged_reuse": True,
                "first_result": first_result,
                "successor_result": fourth_result,
                "source_unchanged": True,
                "external_provider_calls": 0,
                "model_calls": 0,
            },
            indent=2,
        )
    )
    print("manufacturer installed CLI/MCP smoke: ok")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", type=Path, required=True)
    parser.add_argument("--root", type=Path, required=True)
    arguments = parser.parse_args()
    arguments.root = arguments.root.resolve()
    arguments.root.mkdir(parents=True, exist_ok=False)
    anyio.run(exercise, arguments.host, arguments.root)
